### ISSUE TITLE
WJMAIS and Foundry 12 build 331

### ISSUE THREAD

**Issue by tmbigrigg** [surged20/wjmais#31]
I am experiencing an issue with Wildjammer and 
Foundry 12 build 331
5E 4.0.4

This occurs when attempting to drag ship to map. The ship fails to show up on the map and the map then becomes completley unusable and requires deleting the map. When running debugger it indicates potential issue with wjmais and lib-wrapper.

Uncaught TypeError: Cannot read properties of undefined (reading 'Actor')

[Detected 2 packages: wjmais(1.0.2), lib-wrapper(1.13.2.0)]

    at 🎁TokenDocument.prototype.getBarAttribute#wjmais (patch.js:38:41)

    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)

    at 🎁TokenDocument.prototype.getBarAttribute#0 (libWrapper-wrapper.js:193:20)

    at 🎁game.dnd5e.documents.TokenDocument5e.prototype.getBarAttribute#wjmais (patch.js:103:37)

    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)

    at 🎁game.dnd5e.documents.TokenDocument5e.prototype.getBarAttribute#0 (libWrapper-wrapper.js:193:20)

    at foundry.js:60031:34

    at Array.forEach (<anonymous>)

    at Token5e.drawBars (foundry.js:60029:22)

    at Token5e._applyRenderFlags (foundry.js:59721:35)

    at Token5e.applyRenderFlags (foundry.js:26657:10)

    at #applyRenderFlags (foundry.js:26282:44)

    at mn.emit (TickerListener.ts:71:47)

    at Pt.update (Ticker.ts:427:37)

    at Pt._tick (Ticker.ts:129:22)

🎁TokenDocument.prototype.getBarAttribute#wjmais @ patch.js:38

🎁call_wrapper @ libWrapper-wrapper.js:639

🎁TokenDocument.prototype.getBarAttribute#0 @ libWrapper-wrapper.js:193

🎁game.dnd5e.documents.TokenDocument5e.prototype.getBarAttribute#wjmais @ patch.js:103

🎁call_wrapper @ libWrapper-wrapper.js:639

🎁game.dnd5e.documents.TokenDocument5e.prototype.getBarAttribute#0 @ libWrapper-wrapper.js:193

(anonymous) @ foundry.js:60031

drawBars @ foundry.js:60029

_applyRenderFlags @ foundry.js:59721

applyRenderFlags @ foundry.js:26657

#applyRenderFlags @ foundry.js:26282

emit @ TickerListener.ts:71

update @ Ticker.ts:427

Pt._tick @ Ticker.ts:129

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

requestAnimationFrame

Pt._tick @ Ticker.ts:133

**Comment by surged20** [comment]
This should be fixed in https://github.com/surged20/wjmais/releases/tag/1.1.0
